"""Schema for the Pediatric Case Conference Builder.

The app is intentionally schema-driven so educators can change slide labels,
field limits, helper text, and default content without editing Streamlit logic.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, List


DIAGNOSTIC_TABLE_DEFAULT: List[Dict[str, str]] = [
    {
        "Test/Finding": "CBC",
        "Result": "WBC elevated with neutrophil predominance",
        "Interpretation": "Supports inflammation/infection but is not diagnostic alone",
        "Action": "Use with exam, cultures, and imaging to guide next steps",
    },
    {
        "Test/Finding": "CRP/ESR",
        "Result": "Elevated",
        "Interpretation": "Raises concern for invasive bacterial process when paired with symptoms",
        "Action": "Trend only if it will change management",
    },
]

DIFFERENTIAL_TABLE_DEFAULT: List[Dict[str, str]] = [
    {
        "Diagnosis": "Most likely diagnosis",
        "For": "Key history/exam findings support it",
        "Against": "Finding that does not fit cleanly",
        "What would change my mind": "A new result or clinical change",
    },
    {
        "Diagnosis": "Must-not-miss diagnosis",
        "For": "High risk or dangerous if delayed",
        "Against": "Less common or missing classic feature",
        "What would change my mind": "Specific test, exam, or response to therapy",
    },
]

DISEASE_TEACHING_DEFAULT: List[Dict[str, str]] = [
    {
        "What to know": "Typical presentation",
        "Bedside meaning": "How it shows up for the resident overnight",
        "Pitfall": "Anchoring on one symptom too early",
    },
    {
        "What to know": "Diagnosis",
        "Bedside meaning": "Which test changes management",
        "Pitfall": "Ordering broad tests without a question",
    },
    {
        "What to know": "Treatment",
        "Bedside meaning": "First action, escalation point, and disposition",
        "Pitfall": "Missing deterioration while waiting for confirmation",
    },
]


CASE_SLIDES: List[Dict[str, Any]] = [
    {
        "id": "title_goal",
        "label": "Title + goal",
        "export_title": "Case Conference",
        "fields": [
            {
                "key": "presenter_name",
                "label": "Presenter",
                "type": "text",
                "required": True,
                "max_words": 10,
                "default": "Presenter Name",
                "guide": "Used in the archive index and exported documents.",
            },
            {
                "key": "case_title",
                "label": "Case Title",
                "type": "text",
                "required": True,
                "max_words": 16,
                "default": "Fever, Limp, and Refusal to Bear Weight",
                "guide": "Use a teaching title, not identifiable details.",
            },
            {
                "key": "case_setting",
                "label": "Setting",
                "type": "text",
                "required": False,
                "max_words": 18,
                "default": "Emergency department to inpatient pediatrics",
                "guide": "Example: ED, ward, PICU, clinic, nursery, transport, consult.",
            },
            {
                "key": "learning_point",
                "label": "Learning Point for Archive Index",
                "type": "text",
                "required": True,
                "max_words": 22,
                "default": "Use progressive history, exam, and test interpretation to refine a focused differential.",
                "guide": "This appears in the case archive index with presenter and case title.",
            },
            {
                "key": "session_goal",
                "label": "Session Goal",
                "type": "textarea",
                "required": True,
                "max_words": 70,
                "height": 110,
                "default": "Practice clinical reasoning by revealing the case in stages, asking what information matters next, and translating diagnostic results into management decisions.",
                "guide": "Frame what the audience should practice during the case.",
            },
            {
                "key": "reasoning_skill",
                "label": "Primary Reasoning Skill",
                "type": "select",
                "required": True,
                "options": [
                    "Diagnostic reasoning",
                    "Illness scripts",
                    "Test interpretation",
                    "Management under uncertainty",
                    "Stabilization and escalation",
                    "Communication and shared decision-making",
                    "Systems-based practice",
                ],
                "default": "Diagnostic reasoning",
                "guide": "Pick one primary skill so the session stays focused.",
            },
            {
                "key": "privacy_check",
                "label": "Privacy Check",
                "type": "select",
                "required": True,
                "options": ["Yes - de-identified", "Needs review before presenting"],
                "default": "Yes - de-identified",
                "guide": "No names, MRNs, exact dates, unique identifiers, or identifiable images.",
            },
        ],
    },
    {
        "id": "opening_case",
        "label": "Opening case",
        "export_title": "Opening Case",
        "fields": [
            {
                "key": "case_stem",
                "label": "Initial Case Stem",
                "type": "textarea",
                "required": True,
                "max_words": 90,
                "height": 130,
                "default": "A previously healthy toddler presents with fever, irritability, and refusal to bear weight after several days of nonspecific symptoms. The child is uncomfortable but interactive. The team needs to decide what information matters most before choosing tests or treatment.",
                "guide": "Brief setup only. Do not reveal the whole case yet.",
            },
            {
                "key": "initial_question",
                "label": "Opening Audience Question",
                "type": "text",
                "required": True,
                "max_words": 24,
                "default": "What are you most worried about right now?",
                "guide": "This should be answerable before the audience has all the data.",
            },
            {
                "key": "poll_choices",
                "label": "Optional Poll / Answer Choices",
                "type": "textarea",
                "required": False,
                "max_lines": 5,
                "max_words_per_line": 16,
                "height": 120,
                "default": "A. Transient synovitis\nB. Septic arthritis\nC. Osteomyelitis\nD. Trauma\nE. I need more information",
                "guide": "One option per line. Leave blank if not using a poll.",
            },
            {
                "key": "facilitator_prompt",
                "label": "Facilitator Prompt",
                "type": "textarea",
                "required": False,
                "max_words": 55,
                "height": 100,
                "default": "Ask learners to commit to a concern before giving more information. Then show how additional history changes the differential rather than just adding facts.",
                "guide": "Private teaching note for the facilitator guide.",
                "private_note": True,
            },
        ],
    },
    {
        "id": "history_questions",
        "label": "Ask: history",
        "export_title": "What History Do You Need?",
        "fields": [
            {
                "key": "history_prompt",
                "label": "Audience Prompt",
                "type": "text",
                "required": True,
                "max_words": 24,
                "default": "What history questions would help you narrow the differential?",
                "guide": "Ask before revealing the history.",
            },
            {
                "key": "key_history_questions",
                "label": "High-Yield History Questions",
                "type": "textarea",
                "required": True,
                "max_lines": 8,
                "max_words_per_line": 14,
                "height": 170,
                "default": "When did symptoms begin, and what changed today?\nAny trauma, fall, or witnessed injury?\nFever pattern and maximum temperature?\nRefusal to walk versus limp?\nRecent infection or antibiotics?\nImmunization status and exposures?\nPain location and ability to move the joint?\nAny rash, swelling, or systemic symptoms?",
                "guide": "One question per line. These can appear after audience discussion.",
            },
            {
                "key": "history_teaching_note",
                "label": "Facilitator Note",
                "type": "textarea",
                "required": False,
                "max_words": 70,
                "height": 100,
                "default": "Emphasize that good history questions are linked to decisions: infection risk, trauma likelihood, inflammatory disease, urgency, and which test or consult is needed next.",
                "guide": "Private teaching note for facilitator guide.",
                "private_note": True,
            },
        ],
    },
    {
        "id": "history_reveal",
        "label": "Reveal: history",
        "export_title": "History Reveal",
        "fields": [
            {
                "key": "timeline",
                "label": "Timeline",
                "type": "textarea",
                "required": True,
                "max_words": 80,
                "height": 120,
                "default": "Symptoms began with low-grade fever and decreased activity. Over the next two days, the child developed worsening leg pain and refused to walk. There is no known trauma. Oral intake is decreased but urine output is present.",
                "guide": "Use a simple sequence. Avoid too many details.",
            },
            {
                "key": "history_positives",
                "label": "Key Positives",
                "type": "textarea",
                "required": True,
                "max_lines": 6,
                "max_words_per_line": 14,
                "height": 130,
                "default": "Fever\nRefusal to bear weight\nLocalized pain\nDecreased activity\nRecent viral symptoms",
                "guide": "One finding per line.",
            },
            {
                "key": "history_negatives",
                "label": "Key Negatives",
                "type": "textarea",
                "required": True,
                "max_lines": 6,
                "max_words_per_line": 14,
                "height": 130,
                "default": "No known trauma\nNo immunocompromising condition\nNo travel\nNo known tick bite\nNo prior joint disease",
                "guide": "One finding per line. Include negatives that change reasoning.",
            },
            {
                "key": "history_interpretation",
                "label": "History Interpretation",
                "type": "textarea",
                "required": True,
                "max_words": 55,
                "height": 100,
                "default": "Fever plus refusal to bear weight raises concern for infection. Lack of trauma makes injury less likely, but the history alone cannot distinguish joint, bone, muscle, or systemic infection.",
                "guide": "Translate history into diagnostic movement.",
            },
        ],
    },
    {
        "id": "exam_questions",
        "label": "Ask: exam",
        "export_title": "What Physical Exam Matters?",
        "fields": [
            {
                "key": "exam_prompt",
                "label": "Audience Prompt",
                "type": "text",
                "required": True,
                "max_words": 24,
                "default": "What physical exam findings would change your level of concern?",
                "guide": "Ask before revealing the exam.",
            },
            {
                "key": "key_exam_elements",
                "label": "High-Yield Exam Elements",
                "type": "textarea",
                "required": True,
                "max_lines": 8,
                "max_words_per_line": 14,
                "height": 170,
                "default": "General appearance and perfusion\nVital sign pattern\nAbility to bear weight\nPassive and active joint range of motion\nPoint tenderness over bone\nSwelling, warmth, erythema\nNeurovascular status\nSkin exam for rash or wounds",
                "guide": "One exam element per line.",
            },
            {
                "key": "exam_teaching_note",
                "label": "Facilitator Note",
                "type": "textarea",
                "required": False,
                "max_words": 70,
                "height": 100,
                "default": "Push learners to say which exam finding would move them from observation to imaging, labs, antibiotics, consult, or urgent procedure.",
                "guide": "Private teaching note for facilitator guide.",
                "private_note": True,
            },
        ],
    },
    {
        "id": "exam_reveal",
        "label": "Reveal: exam",
        "export_title": "Physical Exam Reveal",
        "fields": [
            {
                "key": "vitals",
                "label": "Vital Signs",
                "type": "textarea",
                "required": True,
                "max_lines": 5,
                "max_words_per_line": 14,
                "height": 115,
                "default": "T 39.1 C\nHR 152\nBP appropriate for age\nRR 28\nSpO2 99% in room air",
                "guide": "One vital sign per line.",
            },
            {
                "key": "focused_exam",
                "label": "Focused Exam Findings",
                "type": "textarea",
                "required": True,
                "max_lines": 8,
                "max_words_per_line": 16,
                "height": 170,
                "default": "Uncomfortable but alert\nRefuses to bear weight\nPain with passive hip motion\nNo obvious deformity\nNo overlying erythema\nDistal pulses intact\nNo focal neurologic deficit",
                "guide": "One finding per line.",
            },
            {
                "key": "exam_interpretation",
                "label": "Exam Interpretation",
                "type": "textarea",
                "required": True,
                "max_words": 60,
                "height": 100,
                "default": "The exam increases concern for a painful deep musculoskeletal process. Fever and refusal to bear weight should keep septic arthritis and osteomyelitis high until evaluated.",
                "guide": "Explain what changed after the exam.",
            },
        ],
    },
    {
        "id": "problem_representation",
        "label": "Problem representation",
        "export_title": "Problem Representation",
        "fields": [
            {
                "key": "one_liner",
                "label": "One-Liner",
                "type": "textarea",
                "required": True,
                "max_words": 45,
                "height": 90,
                "default": "Previously healthy toddler with acute fever, refusal to bear weight, and pain with passive hip motion without clear trauma.",
                "guide": "Age + tempo + key syndrome + risk feature.",
            },
            {
                "key": "illness_script",
                "label": "Illness Script / Pattern",
                "type": "textarea",
                "required": True,
                "max_words": 60,
                "height": 100,
                "default": "This pattern should trigger concern for bone or joint infection, while still considering trauma, inflammatory arthritis, malignancy, and referred abdominal or GU pathology depending on exam and labs.",
                "guide": "What pattern should residents recognize?",
            },
            {
                "key": "pivot_point",
                "label": "Clinical Pivot Point",
                "type": "text",
                "required": True,
                "max_words": 24,
                "default": "The combination of fever and refusal to bear weight changes this from routine limp to urgent evaluation.",
                "guide": "The one finding that changes your urgency.",
            },
            {
                "key": "representation_question",
                "label": "Audience Question",
                "type": "text",
                "required": False,
                "max_words": 24,
                "default": "How would you state the problem in one sentence?",
                "guide": "Optional interactive question.",
            },
        ],
    },
    {
        "id": "differential",
        "label": "Differential",
        "export_title": "Differential Diagnosis",
        "fields": [
            {
                "key": "differential_table",
                "label": "Differential Table",
                "type": "table",
                "required": True,
                "columns": ["Diagnosis", "For", "Against", "What would change my mind"],
                "default": DIFFERENTIAL_TABLE_DEFAULT,
                "max_rows": 6,
                "guide": "Prioritize reasoning over a long list.",
            },
            {
                "key": "must_not_miss",
                "label": "Must-Not-Miss Diagnoses",
                "type": "textarea",
                "required": True,
                "max_lines": 3,
                "max_words_per_line": 16,
                "height": 100,
                "default": "Septic arthritis\nOsteomyelitis\nSepsis or disseminated infection",
                "guide": "Maximum three. What would be dangerous to delay?",
            },
            {
                "key": "differential_teaching_note",
                "label": "Facilitator Note",
                "type": "textarea",
                "required": False,
                "max_words": 70,
                "height": 100,
                "default": "Ask learners to defend what is most likely and what is most dangerous. These are not always the same diagnosis.",
                "guide": "Private teaching note for facilitator guide.",
                "private_note": True,
            },
        ],
    },
    {
        "id": "diagnostic_studies_question",
        "label": "Ask: diagnostics",
        "export_title": "What Diagnostic Studies Would You Order?",
        "fields": [
            {
                "key": "diagnostic_prompt",
                "label": "Audience Prompt",
                "type": "text",
                "required": True,
                "max_words": 24,
                "default": "What would you order first, and what question does each test answer?",
                "guide": "Make learners link tests to decisions.",
            },
            {
                "key": "candidate_studies",
                "label": "Possible Diagnostic Studies",
                "type": "textarea",
                "required": True,
                "max_lines": 8,
                "max_words_per_line": 14,
                "height": 170,
                "default": "CBC with differential\nCRP and ESR\nBlood culture\nPlain radiographs if trauma or bony pain\nUltrasound for joint effusion\nMRI if concern for osteomyelitis\nJoint aspiration if septic arthritis is suspected",
                "guide": "One study per line. Include why only in discussion or next section.",
            },
            {
                "key": "diagnostic_reasoning_note",
                "label": "Facilitator Note",
                "type": "textarea",
                "required": False,
                "max_words": 70,
                "height": 100,
                "default": "The key teaching move is to ask: what result would change management? Avoid turning this into a checklist of every possible test.",
                "guide": "Private teaching note for facilitator guide.",
                "private_note": True,
            },
        ],
    },
    {
        "id": "diagnostic_interpretation",
        "label": "Interpret diagnostics",
        "export_title": "Diagnostic Interpretation",
        "fields": [
            {
                "key": "diagnostic_table",
                "label": "Diagnostic Results and Interpretation",
                "type": "table",
                "required": True,
                "columns": ["Test/Finding", "Result", "Interpretation", "Action"],
                "default": DIAGNOSTIC_TABLE_DEFAULT,
                "max_rows": 6,
                "guide": "Do not just report results. Interpret them.",
            },
            {
                "key": "diagnostic_bottom_line",
                "label": "Diagnostic Bottom Line",
                "type": "textarea",
                "required": True,
                "max_words": 55,
                "height": 100,
                "default": "The available data do not prove the diagnosis alone, but they increase concern enough to treat this as a possible invasive musculoskeletal infection while obtaining definitive evaluation.",
                "guide": "What do the results mean for the patient right now?",
            },
            {
                "key": "diagnostic_pitfall",
                "label": "Interpretation Pitfall",
                "type": "textarea",
                "required": False,
                "max_words": 45,
                "height": 90,
                "default": "A normal early test may not exclude serious disease if the clinical picture is concerning.",
                "guide": "Optional teaching pearl about misinterpretation.",
            },
        ],
    },
    {
        "id": "management_decision",
        "label": "Management",
        "export_title": "Management Decision Point",
        "fields": [
            {
                "key": "management_question",
                "label": "Audience Management Question",
                "type": "text",
                "required": True,
                "max_words": 24,
                "default": "What do you do now while awaiting definitive evaluation?",
                "guide": "Make this practical and time-sensitive.",
            },
            {
                "key": "management_choices",
                "label": "Optional Management Choices",
                "type": "textarea",
                "required": False,
                "max_lines": 5,
                "max_words_per_line": 16,
                "height": 120,
                "default": "A. Observe and repeat exam\nB. Start antibiotics and consult orthopedics\nC. Discharge with close follow-up\nD. Obtain additional imaging first",
                "guide": "One option per line. Leave blank if not using choices.",
            },
            {
                "key": "initial_management",
                "label": "Initial Management",
                "type": "textarea",
                "required": True,
                "max_words": 70,
                "height": 120,
                "default": "Assess stability, treat pain, obtain cultures if indicated, involve the appropriate consultants early, and start empiric antibiotics when clinical suspicion for invasive bacterial infection is high or the child is ill appearing.",
                "guide": "Focus on actions a resident can take.",
            },
            {
                "key": "escalation_disposition",
                "label": "Escalation / Disposition",
                "type": "textarea",
                "required": True,
                "max_words": 55,
                "height": 100,
                "default": "Escalate for hemodynamic instability, rapidly worsening pain, neurovascular concern, need for urgent procedure, or inability to safely monitor and reassess.",
                "guide": "When does this patient need more help or a higher level of care?",
            },
        ],
    },
    {
        "id": "disease_teaching",
        "label": "Disease teaching",
        "export_title": "Disease Teaching",
        "fields": [
            {
                "key": "disease_name",
                "label": "Disease / Syndrome Name",
                "type": "text",
                "required": True,
                "max_words": 12,
                "default": "Pediatric Bone and Joint Infection",
                "guide": "Use the main diagnosis or syndrome.",
            },
            {
                "key": "disease_overview",
                "label": "Brief Disease Overview",
                "type": "textarea",
                "required": True,
                "max_words": 65,
                "height": 110,
                "default": "Bone and joint infections can present with fever, pain, limp, refusal to bear weight, or reduced range of motion. Early recognition matters because delayed treatment can lead to joint destruction, abscess, sepsis, or long-term functional problems.",
                "guide": "What should every resident know?",
            },
            {
                "key": "teaching_table",
                "label": "Disease Teaching Table",
                "type": "table",
                "required": True,
                "columns": ["What to know", "Bedside meaning", "Pitfall"],
                "default": DISEASE_TEACHING_DEFAULT,
                "max_rows": 5,
                "guide": "Keep this practical. Avoid a textbook chapter.",
            },
            {
                "key": "guideline_or_reference_note",
                "label": "Guideline / Evidence Note",
                "type": "textarea",
                "required": False,
                "max_words": 45,
                "height": 90,
                "default": "Local pathways, antimicrobial guidance, and consultant preferences should be checked because management details may vary by institution.",
                "guide": "Optional. Mention local pathway, guideline, or uncertainty.",
            },
        ],
    },
    {
        "id": "major_learning_points",
        "label": "Major points",
        "export_title": "Major Learning Points",
        "fields": [
            {
                "key": "major_points",
                "label": "2-3 Major Take-Home Points",
                "type": "textarea",
                "required": True,
                "max_lines": 3,
                "max_words_per_line": 18,
                "height": 120,
                "default": "Fever plus refusal to bear weight should trigger urgent evaluation for bone or joint infection.\nAsk what each diagnostic test will change before ordering it.\nInterpret results in context; early or nonspecific results do not replace bedside reassessment.",
                "guide": "Exactly 2-3 points. This is the core educational value.",
            },
            {
                "key": "practice_reflection",
                "label": "Practice Reflection Question",
                "type": "text",
                "required": False,
                "max_words": 24,
                "default": "What will you do differently the next time a child presents with limp and fever?",
                "guide": "Prompt residents to connect the case to future practice.",
            },
            {
                "key": "teaching_trap",
                "label": "Common Teaching Trap / Pitfall",
                "type": "textarea",
                "required": False,
                "max_words": 45,
                "height": 90,
                "default": "Do not let the rare diagnosis distract from the reasoning process. The goal is to teach a repeatable approach, not just a memorable case.",
                "guide": "What should the presenter avoid?",
            },
        ],
    },
    {
        "id": "return_to_patient",
        "label": "Return to patient",
        "export_title": "Return to the Patient",
        "fields": [
            {
                "key": "clinical_course",
                "label": "Clinical Course",
                "type": "textarea",
                "required": True,
                "max_words": 80,
                "height": 120,
                "default": "The child was admitted for close monitoring, consultant evaluation, pain control, and antimicrobial therapy. Subsequent imaging and cultures clarified the source, and the team adjusted treatment as additional data returned.",
                "guide": "Summarize what happened without overloading the slide.",
            },
            {
                "key": "final_diagnosis",
                "label": "Final Diagnosis / Working Diagnosis",
                "type": "text",
                "required": True,
                "max_words": 16,
                "default": "Suspected osteoarticular infection",
                "guide": "Use final or best working diagnosis.",
            },
            {
                "key": "outcome_followup",
                "label": "Outcome / Follow-Up",
                "type": "textarea",
                "required": False,
                "max_words": 60,
                "height": 100,
                "default": "The child improved clinically, transitioned to a longer treatment plan, and required follow-up for symptoms, function, and complications.",
                "guide": "Include only details that reinforce the learning point.",
            },
            {
                "key": "systems_learning",
                "label": "Optional Systems / Team Learning",
                "type": "textarea",
                "required": False,
                "max_words": 55,
                "height": 100,
                "default": "Early communication between emergency medicine, pediatrics, orthopedics, radiology, pharmacy, and nursing helped align the plan and reassessment triggers.",
                "guide": "Use if the case has a workflow, safety, or communication lesson.",
            },
        ],
    },
    {
        "id": "final_bottom_line",
        "label": "Bottom line",
        "export_title": "Final Bottom Line",
        "fields": [
            {
                "key": "final_bottom_line",
                "label": "Final Clinical Bottom Line",
                "type": "textarea",
                "required": True,
                "max_words": 60,
                "height": 105,
                "default": "When a child has fever and refusal to bear weight, slow down, build a focused differential, ask what each test will change, and reassess frequently while treating time-sensitive diagnoses seriously.",
                "guide": "One practical takeaway for future patient care.",
            },
            {
                "key": "references",
                "label": "References / Guidelines",
                "type": "textarea",
                "required": False,
                "max_lines": 4,
                "max_words_per_line": 22,
                "height": 130,
                "default": "Local institutional pathway or antimicrobial guideline\nPediatric infectious diseases or orthopedic reference\nRecent review or guideline relevant to the diagnosis",
                "guide": "Use 2-4 sources. This is not a literature review.",
            },
            {
                "key": "feedback_prompt",
                "label": "Feedback Prompt",
                "type": "textarea",
                "required": False,
                "max_words": 45,
                "height": 90,
                "default": "Please complete the brief feedback form so we can keep case conference practical, interactive, and useful for resident learning.",
                "guide": "Appears near the feedback slide and documents.",
            },
        ],
    },
]


def make_default_deck() -> Dict[str, Dict[str, Any]]:
    """Create a default deck dictionary keyed by slide id and field key."""
    deck: Dict[str, Dict[str, Any]] = {}
    for slide in CASE_SLIDES:
        slide_data: Dict[str, Any] = {}
        for field in slide["fields"]:
            if field.get("type") == "table":
                slide_data[field["key"]] = deepcopy(field.get("default", []))
            else:
                slide_data[field["key"]] = deepcopy(field.get("default", ""))
        deck[slide["id"]] = slide_data
    return deck


def archive_summary(deck: Dict[str, Dict[str, Any]]) -> Dict[str, str]:
    """Return the fields that should appear in the archive index."""
    title_data = deck.get("title_goal", {}) if isinstance(deck, dict) else {}
    return {
        "presenter": str(title_data.get("presenter_name", "")).strip(),
        "case": str(title_data.get("case_title", "")).strip(),
        "learning_point": str(title_data.get("learning_point", "")).strip(),
    }
